apiVersion: batch/v1
kind: CronJob
metadata:
  name: locust-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: locust
        spec:
          containers:
          - name: locust
            image: sunwukhan/my-locust-app:latest
            ports:
            - containerPort: 8089
            env:
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: locust-config
                  key: HOST
            - name: USERS
              valueFrom:
                configMapKeyRef:
                  name: locust-config
                  key: USERS
            - name: SPAWN_RATE
              valueFrom:
                configMapKeyRef:
                  name: locust-config
                  key: SPAWN_RATE
            - name: RUN_TIME
              valueFrom:
                configMapKeyRef:
                  name: locust-config
                  key: RUN_TIME
            - name: LOCUST_FILE
              valueFrom:
                configMapKeyRef:
                  name: locust-config
                  key: LOCUST_FILE
          restartPolicy: OnFailure
